import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: `%s | Sai Surya Teja`,
    default: "Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "teal" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "skyblue" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
